market_type: linear
time_start: "20230701"
time_end: "20260101"
stake_amount: 200
wallet_amounts:
  USDT: 3000
pairs: [ETH]
run_policy:
  - name: ma:demo
    run_timeframes: [8h]
    # pairs: [BTC]
    params: {atr: 15}
accounts:
  user1:
    binance:
      prod:
        api_key: ${BNB_API_KEY}
        api_secret: ${BNB_API_SECRET}
